---

- name: Set hostname
  hostname: name={{ hostname }}
  become: true

- name: Add i386 architecture
  lineinfile: path=/var/lib/dpkg/arch line=i386 create=yes
  become: true

- name: Updating package sources information
  apt: update_cache=yes
  become: true

- name: Accepting SteamCMD license
  debconf: name=steamcmd question=steam/question vtype=select value="I AGREE"
  become: true

- name: Installing base packages
  apt: state=latest name={{ packages }}
  become: true
